// 这种方式主要是实现唯一枚举来代替字符串
// export const INCREMENT_COUNTER = Symbol(1);

export const EVT_GETINFO = 'EVT_GETINFO';
export const EVT_SET_GETQUESTION_LIST = 'EVT_SET_GETQUESTION_LIST';
export const EVT_SET_SUBMIT_RESULT = 'EVT_SET_SUBMIT_RESULT';
export const EVT_SET_SUBMIT_INFO_RESULT = 'EVT_SET_SUBMIT_INFO_RESULT';